### ISSUE TITLE
Maintainers?

### ISSUE THREAD

**Issue by tylerturdenpants** [kybishop/ember-popper#107]
do you need maintainers here as well?

**Comment by kybishop** [comment]
Simon has taken over the project for the most part. @simonihmig would you want another hand?

**Comment by simonihmig** [comment]
> would you want another hand?

Oh sure! I have been using this as part of ember-bootstrap, and mostly focused on things I needed there. But if other issues arise, having someone to share the responsibility would be awesome!

**Comment by kybishop** [comment]
It is done :)
