### ISSUE TITLE
How to add preventOverflow

### ISSUE THREAD

**Issue by bojanvidanovic** [kybishop/ember-popper#44]
Hi, and thank for this ember wrapper of the lib.

At the moment it works nicely, except I was wondering how can I add preventOverflow with boundaries (.ember-application in our case)?

Thanks.

**Comment by pzuraq** [comment]
You can pass an object for `modifiers`:

```hbs
{{#ember-popper
  modifiers=(hash
    preventOverflow=(hash
      boundariesElement=".ember-application"
    )
  )
}}
```

`modifiers` just gets directly passed to popper so you can configure it per the [popper docs](https://popper.js.org/popper-documentation.html#modifiers)

**Comment by bojanvidanovic** [comment]
Awesome! Thank again.
