### ISSUE TITLE
Production build fails if sourcemaps are enabled

### ISSUE THREAD

**Issue by urbany** [kybishop/ember-popper#46]
Hi, first of all thanks for this awesome plugin!

I have a project which needs sourcemaps in production builds.
It was working fine in `ember-cli-uglify@1.2.0` but stopped after upgrading to `ember-cli-uglify@2.0.0`.
The build fails if I build for production with sourcemaps enabled (in `ember-cli-build.js`):
```
$ ember build -e production
cleaning up...
Build failed.
The Broccoli Plugin: [Fingerprint] failed with:
Error: ENOENT: no such file or directory, open '/Users/.../popper-test/tmp/uglify_writer-input_base_path-1o0lRxYB.tmp/assets/popper.js.map'
    at Error (native)
    at Object.fs.openSync (fs.js:642:18)
    at Object.fs.readFileSync (fs.js:510:33)
    at UglifyWriter.processFile (/Users/.../popper-test/node_modules/broccoli-uglify-sourcemap/index.js:101:41)
    at /Users/.../popper-test/node_modules/broccoli-uglify-sourcemap/index.js:65:16
    at Array.forEach (native)
    at /Users/.../popper-test/node_modules/broccoli-uglify-sourcemap/index.js:55:25
    at Array.forEach (native)
    at UglifyWriter.build (/Users/.../popper-test/node_modules/broccoli-uglify-sourcemap/index.js:54:19)
    at /Users/.../popper-test/node_modules/broccoli-plugin/read_compat.js:93:34
```

I have a reproduction here: [urbany/ember-popper-sourcemaps-error](https://github.com/urbany/ember-popper-sourcemaps-error)
You can see the error with: `ember build -e production`

This reproduction is a new ember app with just these changes: https://github.com/urbany/ember-popper-sourcemaps-error/commit/9926b349d1cab071ed7ad02c90cd202dcd06265e

I also added an issue here, not sure if this problem is on emper-popper or on the ember-cli pipeline: https://github.com/ember-cli/ember-cli-uglify/issues/29#issuecomment-336085319

Thanks in advance!

EDIT:
After a closer look I can see that in `/Users/.../popper-test/tmp/uglify_writer-input_base_path-1o0lRxYB.tmp/assets/vendor.js` still has this: ```//# sourceMappingURL=popper.js.map```, this should probably be stripped since the `popper.js.map`is already concatenated in the vendor.map

**Comment by simonihmig** [comment]
We have received a similar issue here after having published ember-bootstrap 1.0.0-rc.3 that includes ember-popper as a dependency: https://github.com/kaliber5/ember-bootstrap/issues/468

**Comment by urbany** [comment]
I managed to create a fix while this is not properly fixed:
```
$ ember g in-repo-addon fix-popper
$ npm install --save-dev broccoli-string-replace
```

*my-project/lib/fix-popper/package.json*
```
{
  "name": "fix-popper",
  "keywords": [
    "ember-addon"
  ],
  "dependencies": {
    "broccoli-string-replace": "^0.1.2"
  }
}
```

*my-project/lib/fix-popper/index.js*
```
/* eslint-env node */
'use strict';
const StringReplace = require('broccoli-string-replace');

module.exports = {
  name: 'fix-popper',

  postprocessTree(type, tree) {
    if (type !== 'all') {
      return tree;
    }
    return StringReplace('app', {
      files: ['popper.js'],
      pattern: {
        match: /\/\/# sourceMappingURL=popper.js.map/g,
        replacement: ''
      }
    });
  }
};
```

This will strip the string that makes the build fail: `//# sourceMappingURL=popper.js.map`
I added a branch to the failing repo with this fix also: https://github.com/urbany/ember-popper-sourcemaps-error/tree/fix

**Comment by urbany** [comment]
While we wait for a proper fix this solves it:
*ember-cli-build.js*
```
/* eslint-env node */
'use strict';

const EmberApp = require('ember-cli/lib/broccoli/ember-app');

module.exports = function(defaults) {
  let app = new EmberApp(defaults, {});

  // this import fixes the build
  app.import('node_modules/popper.js/dist/umd/popper.js.map', { destDir: 'assets' });

  return app.toTree();
};
```

**Comment by kybishop** [comment]
Man I really wish GitHub was better about notifying of issues on watched repos 😠 

I'll dig into this today/tomorrow.

**Comment by urbany** [comment]
@kybishop thanks! Just a small update: I talked with @rwjblue on slack and he created this issue: https://github.com/kratiahuja/fastboot-transform/issues/6

**Comment by urbany** [comment]
Working great! Thanks @kybishop

**Comment by andyhot** [comment]
If however someone inspects the generated vendor sourcemaps (for instance using @urbany repo which now pulls in ember-popper#0.6.6 and the production build succeeds), you'll find that they are broken (try the source-map-explorer tool)

Perhaps the workaround of importing the popper.js.map that was mentioned above helps but i haven't tried yet.
