### ISSUE TITLE
Type assertion fails in IE11

### ISSUE THREAD

**Issue by simonihmig** [kybishop/ember-popper#56]
Oh no, me again with this crappy IE issues... 😬

As I said, I updated to the latest ember-popper, and things worked out well so far, but I see tests for IE11 (Saucelabs) failing with `Types must either be a primitive type string, class, validator, or null or undefined, received: [object Element]`. See https://travis-ci.org/kaliber5/ember-bootstrap/jobs/296004049#L2388

I have not digged deeper so far, but I *assume* the exception is thrown [here](https://github.com/ember-decorators/argument/blob/7d2c37cb0d940a119ec36901306b46e0ce332361/addon/-debug/utils/validators.js#L44), caused by `type` decorators like [this](https://github.com/kybishop/ember-popper/blob/c45ef88e6eaea52b414e9193c7aca852f322f923/addon/components/ember-popper-base.js#L74). Seems IE11 is behaving differently here, probably `Element` is not of type "function"!?

**Comment by simonihmig** [comment]
Indeed, I just checked this quickly in an IE11 VM:

![image](https://user-images.githubusercontent.com/1325249/32318948-21443012-bfb9-11e7-8756-b40a20e1266a.png)

**Comment by pzuraq** [comment]
Interesting, it kind of makes sense becausw IE doesn’t support `new` for certain types.

The main question is, can we use `instanceof` in any way to check whether something is an element? If not, it looks like I’ll need to add some new primitive types to @ember-decorators/argument 😕

Sorry about the regressions btw, I’m going to setup Saucelabs on this and ember-decorators, it’s not ok to have these fail for IE11 (unfortunately)

**Comment by simonihmig** [comment]
> The main question is, can we use instanceof in any way to check whether something is an element? 

Seems to work fine:

![image](https://user-images.githubusercontent.com/1325249/32367517-a4fc9b1e-c082-11e7-9880-c5027df6686f.png)

It's just the `typeof` check that's not following the specs I guess...

**Comment by pzuraq** [comment]
@simonihmig I have a fix out for this in @ember-decorators/argument, it's going to require another update here though since some breaking changes have been made there. I'm pretty sure this will work, should be able to get it out by Monday

**Comment by simonihmig** [comment]
Great, thanks!

**Comment by simonihmig** [comment]
Just updated and can confirm the issue is fixed in IE11. Thanks a lot!
