### ISSUE TITLE
Cleanup/Refactoring

### ISSUE THREAD

**Issue by simonihmig** [kybishop/ember-popper#71]
Before I start working on a PR I wanted to discuss this here with you folks. I played a bit recently with this `-in-element` thing, and did this one: https://github.com/kaliber5/ember-in-element-polyfill. This together with https://github.com/DockYard/ember-maybe-in-element would allow to simplify the code base quite a bit. 

Especially I *think* it would allow to drop all the special legacy handling here (effectively moving it to upstream dependencies), so we have just a single unified component that works with Ember 1.13+. The missing hash helper could be polyfilled with https://github.com/cibernox/ember-hash-helper-polyfill btw.

This however does not work all the way down to Ember 1.11. So before hitting stable, I wonder if the minimum Ember version could be raised to at least 1.13 (which is already quite antique! 😬). Some 0.x version could still be supported for Ember 1.11 (probably bug fixes only).

What do you think?

**Comment by pzuraq** [comment]
I would be alright with dropping 1.11 support for v1.0.0, we should be off of it sooner rather than later and we still would have stable point releases to use until then. If worse came to worst, we would be able to fork to continue development until then.

**Comment by simonihmig** [comment]
Sounds good. Any objections to the proposed implementation changes, would you like to see this in a PR? @kybishop ?

**Comment by kybishop** [comment]
This sounds great! Love an opportunity to simplify through  better abstractions
