### ISSUE TITLE
'-start' & '-end' shift ?

### ISSUE THREAD

**Issue by ctjhoa** [kybishop/ember-popper#74]
Hi,

According to the Popper.js doc and some tests, popper.js handle some placement like `bottom-start`.

https://codepen.io/anon/pen/Ozrrmr

In your source you limit the placement to the main value 

`Placement of the popper. One of ['top', 'right', 'bottom', 'left'].`

Is there a reason? Are these placement values should work even if it's undocumented?

Thanks

**Comment by pzuraq** [comment]
I believe the other values can be used and we should probably update the docs to reflect that

**Comment by simonihmig** [comment]
Confirm! Using this, works just fine! (https://github.com/kaliber5/ember-bootstrap/blob/master/addon/components/bs4/bs-dropdown/menu.js#L22-L39

**Comment by ctjhoa** [comment]
Nice thanks!
