### ISSUE TITLE
Cannot read property 'browsers' of undefined

### ISSUE THREAD

**Issue by absemetov** [kybishop/ember-popper#79]
Ember 2.11

**Comment by Owlman145** [comment]
Same in 2.12.3. Wanted to update to remove ember-decorators depreciation, guess that's not possible.

**Comment by Owlman145** [comment]
Bug comes from ember-legacy-class-shim. Seems to check project targets for supported browsers, but AFAIK target.js was implemented in 2.15?

**Comment by pzuraq** [comment]
You can upgrade Ember-CLI without upgrading Ember itself, but I’ll patch the shim upstream as well.

**Comment by pzuraq** [comment]
This should be fixed, I've updated the shim to check for targets existence.
