### ISSUE TITLE
Node 4 support

### ISSUE THREAD

**Issue by simonihmig** [kybishop/ember-popper#84]
#80 dropped support for node 4, at least it declared so in its `package.json`. While EOL is just in a few days, any addons building on top of ember-popper that follow SemVer and have reached a stable version (>1.0) would have to do a major version bump to drop support for it, which is not always desirable. 

This currently at least breaks installation of this addon and any other having it as a dependency under node 4 (without the `--ignore-engines` flag), e.g here: https://travis-ci.org/simplabs/ember-validated-form-buffer/builds/370595623#L531

Is there any good reason for requiring node 6? At first sight, I don't see any code in node-land requiring node 6 features, not here and also not in `ember-decorators`, which as of 2.0 also requires 6+. So a fix could be as simple as updating `engines` (and probably `travis.yml`).

/cc @pzuraq @turbo87

**Comment by pzuraq** [comment]
Given that Node v4 is about to be EOL'd, I don't think it's worth the effort to continue supporting it. I forget the exact reasons for why we dropped support in `ember-decorators`, but it wasn't just out of convenience. Most libraries should major rev anyways as we move forward, numbers are cheap 😄
