### ISSUE TITLE
Deprecation warning on Ember 3.4 from use of sendAction

### ISSUE THREAD

**Issue by ghost** [kybishop/ember-popper#91]
This line in `ember-popper-base.js` triggers deprecation warnings in Ember 3.4. 

https://github.com/kybishop/ember-popper/blob/462532b2ffbb2c5e1d6192859144fd51d96af8ed/addon/components/ember-popper-base.js#L255

Can we change it to `this.registerAPI(this._getPublicAPI())`, given that closure actions are the way now and `sendAction` is deprecated?

I note the ` eslint-disable ember/closure-actions` currently applied, not sure if there was a rationale for this though.

**Comment by kybishop** [comment]
This was a holdover from 1.11 support, but I'm comfortable dropping that support now. Will come up with a PR to do so, or accept #92 if we can get the tests green ;)

**Comment by kybishop** [comment]
closed in #94
