### ISSUE TITLE
Support Angle Bracket Invocation

### ISSUE THREAD

**Issue by simonihmig** [kybishop/ember-popper#98]
While invoking `<EmberPopper>` with Angle Brackets works ootb, applying arbitrary attributes (`<EmberPopper role="menu">`) to the wormholed element does not. Currently only a few selected attributes are supported, and only when passing them as props (see https://github.com/kybishop/ember-popper/blob/master/addon/templates/components/ember-popper.hbs#L8). Supporting the former would require the use of splattributes (`...attributes`) here.

This in turn requires the use of https://github.com/rwjblue/ember-angle-bracket-invocation-polyfill, which would enable support, but only back to Ember 2.12. So the question is if/when ember-popper should properly support Angle Bracket Invocation?

The ember-try test matrix only goes back to Ember 2.16, but IIRC this addon is supposed to support version back to Ember 1.13 (should be documented!). Or can we introduce a new version (breaking change) to add support and drop those older Ember versions?

**Comment by simonihmig** [comment]
@kybishop any thoughts on this?

**Comment by kybishop** [comment]
Hey @simonihmig, I started a full-time gig at a non-Ember startup that leaves me virtually no time for open source stuff. I trust your judgement, you're welcome to do whatever you think is best.

**Comment by simonihmig** [comment]
Oh, good to know. Unfortunate for this project, but hopefully good for you and the startup, wish you luck there! 😀

I would then go forward and create a `release-0.9` branch in case something urgent comes up that needs to be fixed for the current version supporting older Ember versions, and prepare a new breaking change 0.10 release that would drop support for Ember < 2.18, adds the angle bracket polyfill, supports splattributes and drops my in-element polyfill thing for pre-Glimmer. And as such becomes Octane-ready :tada: 

I do have write permissions on Github, but I am not a (co-)owner on npm. @kybishop you want to do the release once ready, or do you want to add me?

PS: @pzuraq IIRC you were using this with some pretty old Ember versions, but I guess this was at your former job (Addepar that was?). Given we retain the ability to add bug fixes for the old release, and your current Octane-involvement, I guess you don't mind this approach?

**Comment by kybishop** [comment]
I'll add you on npm a little later today. You're welcome to merge and release stuff to your heart's content
